/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import auth.Connexion;
import net.proteanit.sql.DbUtils;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextField;
import javax.swing.border.TitledBorder;
import javax.swing.border.EtchedBorder;
import javax.swing.JLabel;
import javax.swing.JComboBox;

/**
 *
 * @author MyLau
 */
public class ProductHome extends javax.swing.JInternalFrame {

    /**
     * Creates new form EmployeHome
     */
    
    public boolean dataStatu;
    public int row;
    String table1_click;

    public void getData(){
        try{

            java.sql.Statement stmt1= maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultat= stmt1.executeQuery("SELECT * FROM products");
	        jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
	
       }catch(Exception e){
	
	
       }
    }
    
   public void getPATSum(){
        try{

            java.sql.Statement stmt1= maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultat= stmt1.executeQuery("SELECT SUM(PAT) FROM products");
	        while(resultat.next()) {
	        	total_PAT_displayer.setText(resultat.getString(1));
	        }
	
       }catch(Exception e){
    	   JOptionPane.showMessageDialog(null,"Error loading total PAT"+ e.toString());
       }
    }
   
   public void getPVTSum(){
       try{

           java.sql.Statement stmt1= maConnexion.ObtenirConnexion().createStatement();
           java.sql.ResultSet resultat = stmt1.executeQuery("SELECT SUM(PVT) FROM products");
	        while(resultat.next()) {
	        	pvt_displayer.setText(resultat.getString(1));
	        }
	
      }catch(Exception e){
   	   JOptionPane.showMessageDialog(null,"Error loading total PVT"+ e.toString());
      }
   }
    

    public ProductHome() {
        initComponents();
        product_expiry_date.setDate(new Date());
        
        setLocation(8,32);
        
        getData();
        getPATSum();
        getPVTSum();
        dataStatu= true;
         SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        product_name.requestFocus();
       
      }
      
    });
         pack();
    }
    Statement stmt;
    Connexion maConnexion= new Connexion();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLNom = new javax.swing.JLabel();
        jLPrenom = new javax.swing.JLabel();
        product_name = new javax.swing.JTextField();
        jLSexe = new javax.swing.JLabel();
        product_sector = new javax.swing.JComboBox();
        jLDateNais = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jBValider = new javax.swing.JButton();
        jBVider = new javax.swing.JButton();
        jBVider.setToolTipText("Reinitializer les champs");
        jBQuitter = new javax.swing.JButton();
        jSupprimer = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jTSearch = new javax.swing.JTextField();
        jLTel1 = new javax.swing.JLabel();

        setClosable(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Détails sur le medicament"));

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations primaire"));

        jLNom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLNom.setForeground(new java.awt.Color(255, 102, 102));
        jLNom.setText("Nom medicament");

        jLPrenom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPrenom.setForeground(new java.awt.Color(255, 102, 102));
        jLPrenom.setText("Prix de vente");

        product_name.setText(" ");
        product_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomActionPerformed(evt);
            }
        });

        jLSexe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLSexe.setForeground(new java.awt.Color(255, 102, 102));
        jLSexe.setText("Secteur");

        product_sector.setModel(new DefaultComboBoxModel(new String[] {"Secteur 1", "Secteur 2", "Secteur 3", "Secteur 4", "Secteur 5", "Secteur 6", "Secteur 7", "Secteur 8", "Secteur 9", "Secteur 10", "Secteur 11", "Secteur 12", "Secteur 13", "Secteur 14", "Secteur 15", "Secteur 16", "Secteur 17", "Secteur 18", "Secteur 19", "Secteur 20"}));
        product_sector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSexeActionPerformed(evt);
            }
        });

        jLDateNais.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLDateNais.setForeground(new java.awt.Color(255, 102, 102));
        jLDateNais.setText("Quantite");
        
        product_quantity = new JTextField();
        product_quantity.setText(" ");
        
        product_price = new JTextField();
        product_price.setText(" ");
        jLPoste = new javax.swing.JLabel();
        
        jLPoste.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLPoste.setForeground(new java.awt.Color(255, 102, 102));
        jLPoste.setText("Date d'expiration");
        product_expiry_date = new com.toedter.calendar.JDateChooser();
        
                product_expiry_date.setDateFormatString("yyyy-MM-dd");
                product_expiry_date.setMinSelectableDate(new java.util.Date(-2208967355000L));
        jLDateEmb = new javax.swing.JLabel();
        
                jLDateEmb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
                jLDateEmb.setForeground(new java.awt.Color(255, 102, 102));
                jLDateEmb.setText("Status");
        product_status = new javax.swing.JComboBox();
        
                product_status.setModel(new DefaultComboBoxModel(new String[] {"Active", "Non active"}));
        
        JLabel lblUnit = new JLabel();
        lblUnit.setText("Unites");
        lblUnit.setForeground(new Color(255, 102, 102));
        lblUnit.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        product_unit = new JComboBox();
        product_unit.setModel(new DefaultComboBoxModel(new String[] {"Flacon", "Sirop adult", "Sirop enfant", "Pce", "Comprimes", "tube", "tube 15g", "tube 30g", "Plaquette"}));
        
        JLabel lblNewLabel = new JLabel("$");
        
        lblPau = new JLabel();
        lblPau.setText("P.A.U");
        lblPau.setForeground(new Color(255, 102, 102));
        lblPau.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        pau_field = new JTextField();
        pau_field.setColumns(10);
        
        JLabel lblPat = new JLabel();
        lblPat.setText("P.A.T");
        lblPat.setForeground(new Color(255, 102, 102));
        lblPat.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        pat_field = new JTextField();
        pat_field.setColumns(10);
        
        lblPvt = new JLabel();
        lblPvt.setText("P.V.T");
        lblPvt.setForeground(new Color(255, 102, 102));
        lblPvt.setFont(new Font("Tahoma", Font.BOLD, 12));
        
        pvt_recup = new JTextField();
        pvt_recup.setColumns(10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLPoste, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLDateEmb)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jLPrenom, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLNom, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(jLDateNais)
        						.addComponent(jLSexe, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblUnit, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
        					.addGap(12)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(product_unit, 0, 139, Short.MAX_VALUE)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(product_price, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblNewLabel))
        						.addComponent(product_quantity, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        						.addComponent(product_sector, Alignment.TRAILING, 0, 139, Short.MAX_VALUE)
        						.addComponent(product_name, GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        						.addComponent(product_expiry_date, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        						.addComponent(product_status, Alignment.TRAILING, 0, 139, Short.MAX_VALUE)))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(lblPau, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(pau_field, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(lblPat, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(pat_field, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(lblPvt, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(pvt_recup, GroupLayout.PREFERRED_SIZE, 141, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLNom, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(product_name, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLPrenom, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(product_price, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLDateNais, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(product_quantity, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(product_sector, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLSexe, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLPoste, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(product_expiry_date, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLDateEmb, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(product_status, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblUnit, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(product_unit, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblPau, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(pau_field, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblPat, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(pat_field, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblPvt, GroupLayout.PREFERRED_SIZE, 24, GroupLayout.PREFERRED_SIZE)
        				.addComponent(pvt_recup, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opérations"));

        jBValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_save.png"))); // NOI18N
        jBValider.setText("Sauver");
        jBValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBValiderActionPerformed(evt);
            }
        });

        jBVider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/new_user.png"))); // NOI18N
        jBVider.setText("Nouveau");
        jBVider.setMaximumSize(new java.awt.Dimension(101, 23));
        jBVider.setMinimumSize(new java.awt.Dimension(101, 23));
        jBVider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBViderActionPerformed(evt);
            }
        });

        jBQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/use_exit.png"))); // NOI18N
        jBQuitter.setText("Sortir");
        jBQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBQuitterActionPerformed(evt);
            }
        });

        jSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_delete.png"))); // NOI18N
        jSupprimer.setText("Supprimer");
        jSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSupprimerActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/user_print.png"))); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jBVider, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBValider, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSupprimer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBValider)
                    .addComponent(jBVider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBQuitter)
                    .addComponent(jSupprimer)
                    .addComponent(jButton1))
                .addGap(62, 62, 62))
        );

        jTable1.setBackground(new java.awt.Color(204, 255, 204));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nom", "Prenom", "Sexe", "DateNais", "NIF", "Poste", "DateEmb.", "Statut", "Salaire"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(new TitledBorder(null, "Rechercher medicament", TitledBorder.LEADING, TitledBorder.TOP, null, null));

        jTSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTSearchKeyReleased(evt);
            }
        });
        
        pau_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCalculatePATKeyReleased(evt);
            }
        });
        
        product_quantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCalculatePVTKeyReleased(evt);
            }
        });

        jLTel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLTel1.setForeground(new java.awt.Color(0, 51, 255));
        jLTel1.setText("Entrer le nom");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLTel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(119, 119, 119)
                .addComponent(jTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTel1))
                .addGap(28, 28, 28))
        );
        
        lblNewLabel_1 = new JLabel("Total PAT :");
        
        total_PAT_displayer = new JLabel("Amount");
        total_PAT_displayer.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        lblNewLabel_2 = new JLabel("$");
        
        lblNewLabel_3 = new JLabel("PVT :");
        
        pvt_displayer = new JLabel("Amount");
        pvt_displayer.setFont(new Font("Tahoma", Font.BOLD, 14));
        
        lblNewLabel_4 = new JLabel("$");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addComponent(jPanel5, GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel6Layout.createSequentialGroup()
        							.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 71, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(total_PAT_displayer)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(lblNewLabel_2)
        							.addGap(18)
        							.addComponent(lblNewLabel_3)
        							.addGap(18)
        							.addComponent(pvt_displayer)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(lblNewLabel_4))
        						.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 904, Short.MAX_VALUE))))
        			.addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 430, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(lblNewLabel_1)
        						.addComponent(total_PAT_displayer)
        						.addComponent(lblNewLabel_2)
        						.addComponent(lblNewLabel_3)
        						.addComponent(pvt_displayer)
        						.addComponent(lblNewLabel_4)))
        				.addComponent(jPanel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE))
        			.addGap(18)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(jPanel5, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jPanel7, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6.setLayout(jPanel6Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel6, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 1258, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        			.addContainerGap())
        );
        getContentPane().setLayout(layout);

        getAccessibleContext().setAccessibleName("jPAppli");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void jTCalculatePATKeyReleased(KeyEvent evt) {
		// TODO Auto-generated method stub
    	String pau_recup = pau_field.getText().trim();
    	String pat_recup = product_quantity.getText().trim();
    	
    	if(pau_recup != "0.") {
    		float unit_price = Float.valueOf(pau_recup);
        	float product_quantty = Float.valueOf(pat_recup);
        	
        	float pat = unit_price * product_quantty;
        	pat_field.setText(pat+"");
    	}
	}
    
    protected void jTCalculatePVTKeyReleased(KeyEvent evt) {
		// TODO Auto-generated method stub
    	String prix_recup = product_price.getText().trim();
    	String quantite_recup = product_quantity.getText().trim();
    	
    	if(quantite_recup != "0") {
    		float int_prix_recup = Float.valueOf(prix_recup);
        	float int_product_quantty = Float.valueOf(quantite_recup);
        	
        	float pvt = int_prix_recup * int_product_quantty;
        	pvt_recup.setText(pvt+"");
    	}
	}

	private void jTNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNomActionPerformed

    private void jCSexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCSexeActionPerformed

    private void jBValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBValiderActionPerformed
        // TODO add your handling code here:
        //*********************************************************

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        String expiry_date_recup = sdf.format(product_expiry_date.getDate());
        String product_name_recup = product_name.getText().toUpperCase().trim();
        String product_price_recup = product_price.getText().trim();
        String product_quantity_recup = product_quantity.getText().trim();
        String product_sector_recup = product_sector.getSelectedItem().toString();
        String product_status_recup = product_status.getSelectedItem().toString();
        String product_unit_recup = product_unit.getSelectedItem().toString();
        String pvt_field_recup = pvt_recup.getText().toUpperCase().trim();
        String pau_recup = pau_field.getText().trim();
        String pat_recup = pat_field.getText().trim();
        if(product_name.getText().trim().length()>0 && product_price.getText().trim().length()>0 && pau_field.getText().trim().length() > 0 && pat_field.getText().trim().length() > 0 && pvt_recup.getText().trim().length() > 0){

        if(dataStatu==true){
            
            try{
            String requete="INSERT INTO products(nom, PV, PVT, quantite, secteur, date_expiration, statut, unite, PAU, PAT)value ('"+product_name_recup+"','"+product_price_recup+"','"+pvt_field_recup+"','"+product_quantity_recup+"','"+product_sector_recup+"','"+expiry_date_recup+"','"+product_status_recup+"','"+product_unit_recup+"','"+pau_recup+"','"+pat_recup+"')";
            stmt=maConnexion.ObtenirConnexion().createStatement();
            stmt.executeUpdate(requete);
            JOptionPane.showMessageDialog(null,"Enregistrement réussi!");
            getPATSum();
            getPVTSum();
        product_name.setText("");
        product_price.setText("");
        product_sector.setSelectedItem("Secteur 1");
        product_status.setSelectedItem("Active");
        product_expiry_date.setDate(new Date());
        product_unit.setSelectedItem("Flacon");
        pau_field.setText("");
        pat_field.setText("");
        pvt_recup.setText("");
            }catch(SQLException | HeadlessException e){
                //JOptionPane.showMessageDialog(null,e);
                JOptionPane.showMessageDialog(null, "Une erreur s'est produite"+e);
                
            }
        }else{
            String requete="UPDATE products  SET nom='"+product_name_recup+"', PV='"+product_price_recup+"', PVT='"+pvt_field_recup+"',quantite='"+product_quantity_recup+"', secteur='"+product_sector_recup+"', "
                 + "date_expiration='"+expiry_date_recup+"', statut='"+product_status_recup+"', unite='"+product_unit_recup+"', PAU='"+pau_recup+"', PAT='"+pat_recup+"' WHERE id='"+table1_click+"'";

      try{
            stmt =maConnexion.ObtenirConnexion().createStatement();
            stmt .executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Modification réussie!");
            getPATSum();
            getPVTSum();
      }catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
      }     
        }
        getData();
        }else{
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs!");
        }   
       
    }//GEN-LAST:event_jBValiderActionPerformed

    private void jBViderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBViderActionPerformed
        // TODO add your handling code here:
        dataStatu=true;
        product_name.setText("");
        product_price.setText("");
        product_sector.setSelectedItem("Secteur 1");
        product_status.setSelectedItem("Active");
        product_expiry_date.setDate(new Date());
        product_unit.setSelectedItem("Flacon");
        pau_field.setText("");
        pat_field.setText("");
        pvt_recup.setText("");
        SwingUtilities.invokeLater(new Runnable() {
      @Override
      public void run() {
        product_name.requestFocus(); 
      }
      
    });
    }//GEN-LAST:event_jBViderActionPerformed

    private void jBQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBQuitterActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jBQuitterActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        dataStatu=false;
        try{
            row =jTable1.getSelectedRow();
            table1_click=(jTable1.getModel().getValueAt(row,0).toString());
            java.sql.Statement stmt1=maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultat= stmt1.executeQuery("SELECT * FROM products WHERE id='"+table1_click+"'");

            if(resultat.next()){
                product_name.setText(resultat.getString("nom"));
                product_price.setText(resultat.getString("PV"));
                product_quantity.setText(resultat.getString("quantite"));
                product_sector.setSelectedItem(resultat.getString("secteur"));
                product_status.setSelectedItem(resultat.getString("statut"));
                product_expiry_date.setDate(resultat.getDate("date_expiration"));
                product_status.setSelectedItem(resultat.getString("statut"));
                product_unit.setSelectedItem(resultat.getString("unite"));
                pau_field.setText(resultat.getString("PAU"));
                pat_field.setText(resultat.getString("PAT"));
                pvt_recup.setText(resultat.getString("PVT"));
            }

        }catch(Exception e){

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSupprimerActionPerformed
        // TODO add your handling code here:
        if(product_name.getText().trim().length()>0 && product_price.getText().trim().length()>0){ 
            String requete="DELETE FROM products WHERE id='"+table1_click+"'";
        try{
            stmt=maConnexion.ObtenirConnexion().createStatement();
            stmt.executeUpdate(requete);
            JOptionPane.showMessageDialog(null, "Suppresion réussie!");         
      }                                           
      catch(SQLException ex){
            System.err.println(ex);
        }
        }else{
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un medicament!");
      
            
        }
        
        product_name.setText("");
        product_price.setText("");
        product_sector.setSelectedItem("Secteur 1");
        product_status.setSelectedItem("Active");
        product_expiry_date.setDate(new Date());
        getData();
    }//GEN-LAST:event_jSupprimerActionPerformed

    private void jTSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTSearchKeyReleased
        // TODO add your handling code here:

        dataStatu=false;
        
        try{
            java.sql.Statement stmt1=maConnexion.ObtenirConnexion().createStatement();
            java.sql.ResultSet resultat= stmt1.executeQuery("SELECT * FROM products where nom LIKE '" + jTSearch.getText().trim() + "%'");
            jTable1.setModel(DbUtils.resultSetToTableModel(resultat));
	
          }catch(Exception e){
	
	
          }
        
    }//GEN-LAST:event_jTSearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        final String daterecup=sdf.format(product_expiry_date.getDate());
        
        if(product_name.getText().trim().length()>0 && product_price.getText().trim().length()>0){
        PrinterJob job = PrinterJob.getPrinterJob();
        job.setPrintable(new Printable() {
 
            @Override
            public int print(Graphics graphics, PageFormat pageFormat, int pageIndex) throws PrinterException {
                if (pageIndex > 0) {
            return NO_SUCH_PAGE;
        }
         
    //Image
                /*BufferedImage image = ImageIO.read(new File(adresseImage));
                graphics.drawImage(image, 0, 0, null);*/
                
    //Image
        int marge=30;
        int x = (int)pageFormat.getImageableX();
        int y = (int)pageFormat.getImageableY();
                 
        graphics.setFont(new Font("Times new roman", Font.BOLD, 20));
        graphics.setColor(Color.BLACK);
        graphics.drawString("                            FICHE \n", x + marge, y + marge);
 
        graphics.drawLine(100, 40, 470, 40);
    
    
        graphics.setFont(new Font("Times New Roman", Font.LAYOUT_LEFT_TO_RIGHT, 18));
        graphics.drawString(" *Nom", 130, 80);        
        graphics.drawString(product_name.getText(), 350, 80);
        
        graphics.drawString(" *Prix", 130, 110);
        graphics.drawString(product_price.getText(), 350, 110);
        
        graphics.drawString(" *Secteur", 130, 140);
        graphics.drawString((String) product_sector.getSelectedItem(), 350, 140);
        
//        graphics.drawString(" *Date Naissance", 130, 170);
//        graphics.drawString(dateNais, 350, 170);
        
//        graphics.drawString(" *Lieu", 130, 200);
//        graphics.drawString(jTLieuNais.getText(), 350, 200);
//        
//        graphics.drawString(" *NIF", 130, 230);
//        graphics.drawString(jFTNIF.getText(), 350, 230);
//        
//        graphics.drawString(" *G. Sanguin", 130, 270);
//        graphics.drawString((String) jCSanguin.getSelectedItem(), 350, 270);
//        
//        graphics.drawString(" *Grade", 130, 300);
//        graphics.drawString((String) jCNEtude.getSelectedItem(), 350, 300);
//             
//        graphics.drawString(" *Poste", 130, 330);
//        graphics.drawString(jTPoste.getText(), 350, 330);
//        
//        graphics.drawString(" *Date Embauche", 130, 360);
//        graphics.drawString(daterecup, 350, 360);
//        
//        graphics.drawString(" *Statut", 130, 390);
//        graphics.drawString((String) product_status.getSelectedItem(), 350, 390);
//        
//        graphics.drawString(" *Salaire", 130, 420);
//        graphics.drawString(jTSalaire.getText()+" Gdes.", 350, 420);
//        
//        graphics.drawString(" *Téléphone", 130, 450);
//        graphics.drawString(jFTTel.getText(), 350, 450);
//        
//        graphics.drawString(" *Email", 130, 480);
//        graphics.drawString(jTEmail.getText(), 350, 480);

        return PAGE_EXISTS;
            }
 
        });
boolean doPrint = job.printDialog();
if(doPrint) {
    try {
         
        job.print();
    }
    catch (PrinterException e1) {
            JOptionPane.showMessageDialog(null, e1);
    }
}}else{
            JOptionPane.showMessageDialog(null, "Veuillez sélectionner un produit!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBQuitter;
    private javax.swing.JButton jBValider;
    private javax.swing.JButton jBVider;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox product_status, product_unit, product_sector;
    private javax.swing.JLabel jLDateEmb;
    private javax.swing.JLabel jLDateNais;
    private javax.swing.JLabel jLNom;
    private javax.swing.JLabel jLPoste;
    private javax.swing.JLabel jLPrenom;
    private javax.swing.JLabel jLSexe;
    private javax.swing.JLabel jLTel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jSupprimer;
    private com.toedter.calendar.JDateChooser product_expiry_date;
    private javax.swing.JTextField product_name;
    private javax.swing.JTextField jTSearch;
    private javax.swing.JTable jTable1;
    private JTextField product_quantity;
    private JTextField product_price;
    private JLabel lblPau;
    private JTextField pau_field;
    private JTextField pat_field;
    private JLabel lblNewLabel_1;
    private JLabel total_PAT_displayer;
    private JLabel lblNewLabel_2;
    private JLabel lblPvt;
    private JTextField pvt_recup;
    private JLabel lblNewLabel_3;
    private JLabel pvt_displayer;
    private JLabel lblNewLabel_4;
}
